### ISSUE TITLE
ENH: add `sinc`

### ISSUE THREAD

**Issue by lucascolley** [data-apis/array-api-extra#16]
x-ref https://github.com/scipy/scipy/pull/21783#discussion_r1829177161

**Comment by asmeurer** [comment]
Does everyone use the normalized definition of sinc?

**Comment by lucascolley** [comment]
The array libraries we test with in SciPy all follow NumPy in using the normalized definition.

We could add a `normalized=True` kwarg if the unnormalized use-case ever arose?

**Comment by asmeurer** [comment]
Not unless that is already common. It doesn't look like NumPy has it. You can always divide by pi if you want an unnormalized sinc. 

My main concern is whether we would be deciding on a convention here, or whether that convention has effectively already been decided by the community.

**Comment by lucascolley** [comment]
> My main concern is whether we would be deciding on a convention here, or whether that convention has effectively already been decided by the community.

My two cents is that this library is not trying to weigh in on conventions at all, it is just taking what is used out in the wild and making that accessible in the array-agnostic context. If multiple conventions are used for some function name we should support all common use cases. If/when an API is considered for the standard is when there is a decision on convention.

It sounds like @rgommers would roughly agree from https://github.com/data-apis/array-api-extra/pull/10#issuecomment-2439874054.
