### ISSUE TITLE
Collecting feedback to inform Array API standard?

### ISSUE THREAD

**Issue by mdhaber** [data-apis/array-api-extra#9]
I'd suggest that we implement a way of collecting information about usage of `array-api-extra` to inform changes/additions to the array API standard. This doesn't have to be automatic; it could be as simple as documenting a procedure for users to comment on what they are using a given function for and why the existing standard was not enough for them.

The simplest thing I can think of would be to include a standard note in function documentation requesting that users leave a note somewhere (e.g. an issue that corresponds with each function) or fill out a form. Perhaps this could get more sophisticated in time, but maybe start with something as simple as this?

My guess is that you'd get more comments like https://github.com/data-apis/array-api-extra/pull/7#issuecomment-2371828099 (which points out that having `expand_dims` accept more than one `axis` is useful and not complicated for any backend to support). Comments in support of features and example use cases are helpful when it's time to file an issue at [`data-apis/array-api`](https://github.com/data-apis/array-api/).

**Comment by lucascolley** [comment]
I'm basically happy with whatever the array API maintainers would fine useful w.r.t. this

**Comment by asmeurer** [comment]
I think anyone who is going to do that will be open source on GitHub anyways. We can use GitHub code search or maybe the API to do this. We've already done this sort of thing in the past to inform array API decisions https://github.com/data-apis/python-record-api

**Comment by mdhaber** [comment]
Right, and I've done that before, too. It might still be useful for users to report this sort of thing:
- it gives us a pulse of what functions are being used (although perhaps it is easy enough to periodically search for all of them)
- it gives us English descriptions of why users felt the need to use them (which we *could* get by reaching out and asking)

So it's not information that we can't get otherwise, but it offloads a little work from us and gives users a mechanism for less formal feedback than an RFC at [data-apis/array-api](https://github.com/data-apis/array-api/).

**Comment by asmeurer** [comment]
I don't see any issues with asking people to report issues or feedback in the documentation. That's something I usually do anyways. I'm -1 to any sort of actual "analytics".

**Comment by mdhaber** [comment]
Sounds good. Changed the title accordingly.

**Comment by lucascolley** [comment]
feel free to send a PR asking for this in the documentation Matt (or anyone else)

**Comment by mdhaber** [comment]
I think I'll withdraw the comment, actually. A month later, it doesn't seem as important to me.
